export const DEFAULT_WINDOWS_CLEAN_FONT_FILES = new Set([
  // Core Latin
  'arial.ttf', 'arialbd.ttf', 'arialbi.ttf', 'ariali.ttf', 'ariblk.ttf',
  'bahnschrift.ttf',
  'calibri.ttf', 'calibrib.ttf', 'calibrii.ttf', 'calibril.ttf', 'calibrili.ttf', 'calibriz.ttf',
  'cambria.ttc', 'cambriab.ttf', 'cambriai.ttf', 'cambriaz.ttf',
  'candara.ttf', 'candarab.ttf', 'candarai.ttf', 'candaral.ttf', 'candarali.ttf', 'candaraz.ttf',
  'comic.ttf', 'comicbd.ttf', 'comici.ttf', 'comicz.ttf',
  'consola.ttf', 'consolab.ttf', 'consolai.ttf', 'consolaz.ttf',
  'constan.ttf', 'constanb.ttf', 'constani.ttf', 'constanz.ttf',
  'corbel.ttf', 'corbelb.ttf', 'corbeli.ttf', 'corbell.ttf', 'corbelli.ttf', 'corbelz.ttf',
  'cour.ttf', 'courbd.ttf', 'courbi.ttf', 'couri.ttf',
  'ebrima.ttf', 'ebrimabd.ttf',
  'framd.ttf', 'framdit.ttf',
  'gabriola.ttf',
  'gadugi.ttf', 'gadugib.ttf',
  'georgia.ttf', 'georgiab.ttf', 'georgiai.ttf', 'georgiaz.ttf',
  'holomdl2.ttf',
  'impact.ttf',
  'inkfree.ttf',
  'javatext.ttf',
  'leelawad.ttf', 'leelawdb.ttf', 'leeluisl.ttf',
  'lucon.ttf',
  'l_10646.ttf',
  'malgun.ttf', 'malgunbd.ttf', 'malgunsl.ttf',
  'marlett.ttf',
  'micross.ttf',
  'mmrtext.ttf', 'mmrtextb.ttf',
  'monbaiti.ttf',
  'msgothic.ttc',
  'msjh.ttc', 'msjhbd.ttc', 'msjhl.ttc',
  'msyh.ttc', 'msyhbd.ttc', 'msyhl.ttc',
  'mvboli.ttf',
  'ntailu.ttf', 'ntailub.ttf',
  'phagspa.ttf', 'phagspab.ttf',
  'segmdl2.ttf',
  'segoepr.ttf', 'segoeprb.ttf',
  'segoesc.ttf', 'segoescb.ttf',
  'segoeui.ttf', 'segoeuib.ttf', 'segoeuii.ttf', 'segoeuil.ttf', 'segoeuisl.ttf', 'segoeuiz.ttf',
  'seguibl.ttf', 'seguibli.ttf', 'seguiemj.ttf', 'seguihis.ttf', 'seguili.ttf', 'seguisb.ttf',
  'seguisbi.ttf', 'seguisli.ttf', 'seguisym.ttf', 'seguiemj.ttf',
  'simsun.ttc', 'simsunb.ttf', 'simsunextg.ttf',
  'deng.ttf', 'dengb.ttf', 'dengl.ttf',
  'simfang.ttf', 'simkai.ttf', 'simhei.ttf', 'simli.ttf', 'simyou.ttf',
  'himalaya.ttf', 'msyi.ttf', 'nirmala.ttf', 'nirmalab.ttf', 'nirmalas.ttf',
  'notosanssc-vf.ttf',
  'sylfaen.ttf',
  'symbol.ttf',
  'tahoma.ttf', 'tahomabd.ttf',
  'taile.ttf', 'taileb.ttf',
  'times.ttf', 'timesbd.ttf', 'timesbi.ttf', 'timesi.ttf',
  'trebuc.ttf', 'trebucbd.ttf', 'trebucbi.ttf', 'trebucit.ttf',
  'verdana.ttf', 'verdanab.ttf', 'verdanai.ttf', 'verdanaz.ttf',
  'webdings.ttf',
  'wingding.ttf',
  'yugothb.ttc', 'yugothl.ttc', 'yugothm.ttc', 'yugothr.ttc',
  // East Asian / optional in common zh-CN installs
  'mingliu.ttc', 'mingliub.ttc',
  'msmincho.ttc',
  'batang.ttc', 'gulim.ttc',
  // Windows 11 / newer common defaults
  'segoeuihis.ttf', 'seguihis.ttf',
  'seguiflu.ttf',
  'seguisym.ttf'
])
