import { createRequire } from "node:module";
import { createMainCompositionFeedback } from './bootstrap/mainCompositionFeedback';
import { createMainMutationCompositionRuntime } from './bootstrap/mainMutationCompositionRuntime';
import { createMainOperationsCompositionRuntime } from './bootstrap/mainOperationsCompositionRuntime';




import { registerMainProcessRuntime } from "./app/mainProcessRuntimeRegistration";


import { createMainRuntimeRegistrationPayload } from "./bootstrap/mainRuntimeRegistrationPayload";


import {
  CACHE_ARCHITECTURE_VERSION
} from "./cache/constants";


















import { createTagMetadataRevisionBarrierRuntime } from "./library/tagMetadataRevisionBarrierRuntime";

import { createTagMutationStateSignalRuntime } from "./library/tagMutationStateSignalRuntime";

import { createTagMutationWriteProtocolRuntime } from "./library/tagMutationWriteProtocolRuntime";










import {
  APP_ID,
  APP_NAME,
  BUILD_MARKER,
  CPU_COUNT,
  LOCAL_SCAN_WORKERS,
  LOG_SCHEMA_VERSION,
  NETWORK_SCAN_WORKERS,
  SCAN_STAT_CONCURRENCY,
  SCAN_WORKER_BATCH_SIZE,
  STARTUP_BACKGROUND_TASKS_ENABLED,
  STARTUP_DB_MAINTENANCE_IDLE_DELAY_MS,
  WATCHER_STARTUP_GRACE_MS,
  WINDOWS_STORAGE_MEDIA_DETECT_ENABLED
} from "./app/appRuntimeConfig";

import { createMainCoreCompositionRuntime } from './bootstrap/mainCoreCompositionRuntime';

import { createMainDataCompositionRuntime } from './bootstrap/mainDataCompositionRuntime';

const nodeRequire = createRequire(import.meta.url);

const feedback = createMainCompositionFeedback();
const coreComposition = createMainCoreCompositionRuntime(feedback.core);

const { execFileAsync, delayToEventLoop, migrationDiagnosticsRuntime, rustCoreWorkerRuntime } = coreComposition;

const { dataRoot, dataPath, exists } = coreComposition.paths;

const { appendStartupLog, logPath, flushStartupLogAsync, flushStartupLogSync } = coreComposition.logging;

const {
  safeManagedFontName,
  registryNameFor,
  safeTemporaryActiveFontName,
  temporaryActiveRegistryNameFor,
  normalizeCompareText,
  isUsableInstalledNameCandidate,
  isTemporaryActiveInstalledRecord,
  buildInstalledFontLookupIndex,
  compareFontInstalledWithLookupIndex,
  isPathInWindowsFonts,
  isSystemInstalledRecord,
  isCleanWindowsDefaultCompareResult,
  compareFontInstalledWithList,
} = coreComposition.comparison;

const {
  markRendererUserActivity,
  reportRendererLongTask,
  reportPerformanceEvent,
  isRendererUserActive,
  rendererIdleInMs,
  waitForRendererIdle,
  rendererActivityReason,
  recheckGlobalIoQueues,
  globalIoSnapshot,
  withGlobalIo,
  ioLaneSummary,
  startPerformanceLogSampler,
  stopPerformanceLogSampler,
  flushPerformanceLogs,
} = coreComposition.performance;

const {
  showExistingWindow,
  registerFontProtocol,
  createWindow,
  requestRendererWindowsCloseForQuit,
  sendToRendererWindows,
  createFontScanJobId,
  emitFontIndexProgress,
  createInstallStatusRefreshJobId,
  emitInstallStatusProgress,
  ensureWindows,
  currentUserFontsDir,
  windowsFontsDir,
  resolveExistingFontFilePath,
  authorizeFontRead,
  authorizePhysicalFolderParent,
  authorizePhysicalFolderRename,
  authorizeFontMoveSource,
  authorizeFontMoveTarget,
  authorizeFontMoveDestination,
  authorizeManagedFontDelete,
  missingFontPreviewDataUri,
  loadTemporaryActiveFonts,
  saveTemporaryActiveFonts,
  addFontResourceSessionBatch,
  removeFontResourceSessionBatch,
  writeFontRegistryValuesHKCUBatch,
  deleteFontRegistryValuesHKCUBatch,
  addFontResourceSession,
  removeFontResourceSession,
  deleteRegistryValueHKCU,
  requestFontRefresh,
  broadcastFontChange,
  scheduleBackgroundFontRefreshTail,
  advancedFontRefresh,
} = coreComposition.windows;

const { storageProfileForPath, scanWorkerCount } = coreComposition.storage;

const {
  beginStartupSessionSync,
  markCleanShutdownSync,
  ensureDataRootSync,
  migrateLegacyUserDataIfNeeded
} = coreComposition.lifecycle;

const { dataRootErrorMessage } = coreComposition.capabilities;

const tagMetadataRevisionBarrier = createTagMetadataRevisionBarrierRuntime({
  appendStartupLog,
});

const tagMutationStateSignalRuntime = createTagMutationStateSignalRuntime({
  tagMetadataRevisionBarrier,
  clearFontQueryCaches: feedback.clearFontQueryCaches,
  appendStartupLog,
});

const tagMutationWriteProtocolRuntime = createTagMutationWriteProtocolRuntime({
  tagMetadataRevisionBarrier,
  clearFontQueryCaches: feedback.clearFontQueryCaches,
  appendStartupLog,
});
feedback.bindTags({ onDaemonDomainEvent: (event) => tagMutationStateSignalRuntime.handleRustCoreDaemonDomainEvent(event) });

const dataComposition = createMainDataCompositionRuntime({
  execFileAsync,
  windowsFontsDir,
  currentUserFontsDir,
  resolveExistingFontFilePath,
  rustCoreWorkerRuntime,
  normalizeCompareText,
  isUsableInstalledNameCandidate,
  withGlobalIo,
  delayToEventLoop,
  appendStartupLog,
  dataPath,
  nodeRequire,
  exists,
  tagMutationStateSignalRuntime,
  dataRoot,
  isCleanWindowsDefaultCompareResult,
  completeBackgroundTask: feedback.tasks.completeBackgroundTask,
  isSystemInstalledRecord,
  isPathInWindowsFonts,
  tagMetadataRevisionBarrier,
  migrationDiagnosticsRuntime,
  ensureWindows,
  authorizeFontRead,
  previewTaskKey: feedback.tasks.previewTaskKey,
  skipBackgroundTask: feedback.tasks.skipBackgroundTask,
  upsertBackgroundTask: feedback.tasks.upsertBackgroundTask,
  startBackgroundTask: feedback.tasks.startBackgroundTask,
  heartbeatBackgroundTask: feedback.tasks.heartbeatBackgroundTask,
  failBackgroundTask: feedback.tasks.failBackgroundTask,
  missingFontPreviewDataUri,
  listPhysicalFolderTree: feedback.listPhysicalFolderTree,
});

const {
  clearInstalledFontsMemoryCache,
  getSystemInstalledFonts,
  getSystemInstalledFontsCached,
  scanSystemInstalledFonts,
  rootCacheDir,
  rootIndexDbDir,
  rootIndexDbPath,
  rootEventsDbPath,
  rootHashDbPath,
  rootMetricsDbPath,
  rootCacheLockDir,
  rootPreviewCacheDir,
  legacyRootPreviewCacheDir,
  rootPreviewImageDir,
  rootPreviewDbPath,
  fallbackPreviewImageDir,
  localPreviewImageDir,
  cacheKeyForRootFile,
  isIgnoredWatcherPath,
  sanitizeCachedFont,
  cachedFontForRuntime,
  cacheEntryRuntimePath,
  librarySqlitePath,
  tasksSqlitePath,
  previewSqlitePath,
  kvsSqlitePath,
  eventsSqlitePath,
  hashSqlitePath,
  metricsSqlitePath,
  backupsRootPath,
  maintenanceStatePath,
  closeSqliteDb,
  recoveryMessage,
  sqliteQuickCheck,
  openStableSqliteDb,
  quarantineSqliteFiles,
  restoreLatestDatabaseBackupForLabel,
  openRecoverableApplicationSqliteDb,
  updateSharedFontMetadataEntries,
  renameSharedTagInMetadataIndexes,
  removeSharedTagFromMetadataIndexes,
  sharedMetadataDbPathForRoot,
  openSharedMetadataDb,
  ensureSharedTagOpsBackfilledInOpenDb,
  ensureSharedTagOpsReplayedInOpenDb,
  readSharedTagOpsDiagnosticsInOpenDb,
  readSharedTagOpsConflictReportInOpenDb,
  readSharedMetadataMigrationDiagnosticsInOpenDb,
  repairSharedMetadataInOpenDb,
  initializeRootEventsDb,
  initializeRootHashDb,
  initializeRootMetricsDb,
  initializePreviewDb,
  openPreviewDb,
  getOpenPreviewDb,
  closePreviewDb,
  openLibraryDb,
  getOpenLibraryDb,
  closeLibraryDb,
  loadLibraryShellFromSqlite,
  setLocalFontTagsBase,
  setLocalFontTagsBatchBase,
  deleteLocalFontTagBase,
  loadLibrary,
  loadLibraryShell,
  openKvsDb,
  setCacheKvs,
  openEventsDb,
  recordCacheEvent,
  openHashDb,
  upsertFontHashIndex,
  openMetricsDb,
  cacheArchitectureInfo,
  initializeCacheArchitectureV2,
  checkpointOpenCacheDbs,
  closeCacheDb,
  rootForFontPath,
  saveInstalledTotalSummaryForRoots,
  readInstalledTotalSummaryForRoots,
  readInstallStatusIndex,
  getInstallStatusIndexSnapshot,
  saveInstallStatusIndex,
  openRootIndexDb,
  saveRootIndexSqliteChanges,
  writeRootCacheManifest,
  withRootCacheWriteLock,
  resolveActiveRootIndexDbPath,
  inspectRootIndexSnapshotMaintenance,
  cleanupRootIndexSnapshotMaintenance,
  loadLegacyScanCache,
  hideDirectoryOnWindows,
  writeRootPreviewCacheManifest,
  ensureRootScanCacheStorage,
  saveScanCacheFile,
  getCacheStats,
  clearScanCache,
  clearPreviewCache,
  ensureSqliteColumn,
  loadFolderCache,
  invalidateSharedFontRuntimeCaches,
  loadSharedFontsForFolders,
  appWatchedFolders,
} = dataComposition.storage;

const {
  queryFontPageInLibrary,
  clearFontQueryCaches,
  searchFontsInLibrary,
  syncMergedIndexAfterInstallStatusRefresh,
  syncMergedIndexForRootIncremental,
  syncMergedIndexForRootSnapshot,
  findFontItemInRootIndexes,
  mainProcessFontIndexContains,
  queryFontsInLibrary,
  getFontMetricsFromLibrary,
} = dataComposition.query;

const {
  getPreviewCacheStatus,
  ensureFontPreviewImageFile,
  readPreviewFontData,
  renderFontPreviewImage,
  readCachedFontPreviewImage,
  readCachedFontPreviewImages,
  ensureFontPreviewCache,
} = dataComposition.preview;
feedback.bindData({ appWatchedFolders, mainProcessFontIndexContains, clearFontQueryCaches });

const mutationComposition = createMainMutationCompositionRuntime({
  tagMutationWriteProtocolRuntime: tagMutationWriteProtocolRuntime,
  setLocalFontTagsBase: setLocalFontTagsBase,
  invalidateSharedFontRuntimeCaches: invalidateSharedFontRuntimeCaches,
  setLocalFontTagsBatchBase: setLocalFontTagsBatchBase,
  deleteLocalFontTagBase: deleteLocalFontTagBase,
  saveInstallStatusIndex: saveInstallStatusIndex,
  appWatchedFolders: appWatchedFolders,
  rootForFontPath: rootForFontPath,
  syncMergedIndexAfterInstallStatusRefresh: syncMergedIndexAfterInstallStatusRefresh,
  clearFontQueryCaches: clearFontQueryCaches,
  appendStartupLog: appendStartupLog,
  dataPath: dataPath,
  dataRoot: dataRoot,
  ensureWindows: ensureWindows,
  currentUserFontsDir: currentUserFontsDir,
  isTemporaryActiveInstalledRecord: isTemporaryActiveInstalledRecord,
  compareFontInstalledWithList: compareFontInstalledWithList,
  clearInstalledFontsMemoryCache: clearInstalledFontsMemoryCache,
  getSystemInstalledFontsCached: getSystemInstalledFontsCached,
  readInstallStatusIndex: readInstallStatusIndex,
  loadTemporaryActiveFonts: loadTemporaryActiveFonts,
  saveTemporaryActiveFonts: saveTemporaryActiveFonts,
  safeTemporaryActiveFontName: safeTemporaryActiveFontName,
  temporaryActiveRegistryNameFor: temporaryActiveRegistryNameFor,
  removeFontResourceSession: removeFontResourceSession,
  removeFontResourceSessionBatch: removeFontResourceSessionBatch,
  addFontResourceSessionBatch: addFontResourceSessionBatch,
  writeFontRegistryValuesHKCUBatch: writeFontRegistryValuesHKCUBatch,
  deleteFontRegistryValuesHKCUBatch: deleteFontRegistryValuesHKCUBatch,
  deleteRegistryValueHKCU: deleteRegistryValueHKCU,
  requestFontRefresh: requestFontRefresh,
  advancedFontRefresh: advancedFontRefresh,
  addFontResourceSession: addFontResourceSession,
  scheduleBackgroundFontRefreshTail: scheduleBackgroundFontRefreshTail,
  withGlobalIo: withGlobalIo,
  delayToEventLoop: delayToEventLoop,
  rustCoreWorkerRuntime: rustCoreWorkerRuntime,
  windowsFontsDir: windowsFontsDir,
  registryNameFor: registryNameFor,
  normalizeCompareText: normalizeCompareText,
  getSystemInstalledFonts: getSystemInstalledFonts,
  sharedMetadataDbPathForRoot: sharedMetadataDbPathForRoot,
  exists: exists,
  openStableSqliteDb: openStableSqliteDb,
  closeSqliteDb: closeSqliteDb,
  openLibraryDb: openLibraryDb,
  loadLibraryShellFromSqlite: loadLibraryShellFromSqlite,
  syncMergedIndexForRootIncremental: syncMergedIndexForRootIncremental,
  syncMergedIndexForRootSnapshot: syncMergedIndexForRootSnapshot,
  updateSharedFontMetadataEntries: updateSharedFontMetadataEntries,
  removeSharedTagFromMetadataIndexes: removeSharedTagFromMetadataIndexes,
  renameSharedTagInMetadataIndexes: renameSharedTagInMetadataIndexes,
  safeManagedFontName: safeManagedFontName,
  findFontItemInRootIndexes: findFontItemInRootIndexes,
  authorizeManagedFontDelete: authorizeManagedFontDelete,
  broadcastFontChange: broadcastFontChange,
  authorizePhysicalFolderParent: authorizePhysicalFolderParent,
  authorizePhysicalFolderRename: authorizePhysicalFolderRename,
  refreshWatchedFolder: feedback.refreshWatchedFolder,
  resolveExistingFontFilePath: resolveExistingFontFilePath,
  authorizeFontMoveSource: authorizeFontMoveSource,
  authorizeFontMoveTarget: authorizeFontMoveTarget,
  authorizeFontMoveDestination: authorizeFontMoveDestination,
  saveLibrary: dataComposition.storage.saveLibrary,
  sendFontIndexChanged: feedback.sendFontIndexChanged,
});
const {
  saveLibrary,
  installFontSystemWide,
  uninstallFontSystemWide,
  deleteFontFilesToTrash,
  setFontDeleteProtectionInIndex,
  setSharedFontFavoriteInIndex,
  setLocalFontTags,
  setLocalFontTagsBatch,
  deleteLocalFontTag,
  setSharedFontTagsInIndex,
  setSharedFontTagsBatchInIndex,
  renameSharedFontTagInIndex,
  deleteSharedFontTagInIndex,
  activateFontSession,
  activateFontSessionsBatch,
  deactivateFontSession,
  deactivateFontSessionsBatch,
  installFontForCurrentUser,
  uninstallManagedFont,
  createPhysicalFolder,
  renamePhysicalFolder,
  moveFontFileToFolder,
  moveFontFilesToFolder
} = mutationComposition.capabilities;
const {
  cleanupTemporaryActiveFontsUntilEmpty,
  flushPendingTemporaryFontDeletes,
  flushActivationInstallStatusSave,
  hasPendingActivationInstallStatusSave,
  hasInFlightActivationInstallStatusSave
} = mutationComposition.lifecycle;
const { listPhysicalFolderTree, refreshKnownSharedTagsFromMetadata } = mutationComposition;
feedback.bindMutation({ listPhysicalFolderTree });

const operationsComposition = createMainOperationsCompositionRuntime({
  tasksSqlitePath: tasksSqlitePath,
  openRecoverableApplicationSqliteDb: openRecoverableApplicationSqliteDb,
  closeSqliteDb: closeSqliteDb,
  ensureSqliteColumn: ensureSqliteColumn,
  getOpenLibraryDb: getOpenLibraryDb,
  appendStartupLog: appendStartupLog,
  findFontItemInRootIndexes: findFontItemInRootIndexes,
  getSystemInstalledFontsCached: getSystemInstalledFontsCached,
  compareFontInstalledWithList: compareFontInstalledWithList,
  saveInstallStatusIndex: saveInstallStatusIndex,
  ensureFontPreviewImageFile: ensureFontPreviewImageFile,
  withGlobalIo: withGlobalIo,
  syncMergedIndexForRootSnapshot: syncMergedIndexForRootSnapshot,
  delayToEventLoop: delayToEventLoop,
  sendToRendererWindows: sendToRendererWindows,
  isRendererUserActive: isRendererUserActive,
  rendererIdleInMs: rendererIdleInMs,
  rendererActivityReason: rendererActivityReason,
  appWatchedFolders: appWatchedFolders,
  loadSharedFontsForFolders: loadSharedFontsForFolders,
  readInstallStatusIndex: readInstallStatusIndex,
  readInstalledTotalSummaryForRoots: readInstalledTotalSummaryForRoots,
  saveInstalledTotalSummaryForRoots: saveInstalledTotalSummaryForRoots,
  rustCoreWorkerRuntime: rustCoreWorkerRuntime,
  buildInstalledFontLookupIndex: buildInstalledFontLookupIndex,
  compareFontInstalledWithLookupIndex: compareFontInstalledWithLookupIndex,
  rootForFontPath: rootForFontPath,
  syncMergedIndexAfterInstallStatusRefresh: syncMergedIndexAfterInstallStatusRefresh,
  clearFontQueryCaches: clearFontQueryCaches,
  emitInstallStatusProgress: emitInstallStatusProgress,
  waitForRendererIdle: waitForRendererIdle,
  execFileAsync: execFileAsync,
  windowsFontsDir: windowsFontsDir,
  currentUserFontsDir: currentUserFontsDir,
  createInstallStatusRefreshJobId: createInstallStatusRefreshJobId,
  assertFeedbackReady: feedback.assertReady,
  refreshKnownSharedTagsFromMetadata: refreshKnownSharedTagsFromMetadata,
  exists: exists,
  sharedMetadataDbPathForRoot: sharedMetadataDbPathForRoot,
  openSharedMetadataDb: openSharedMetadataDb,
  ensureSharedTagOpsBackfilledInOpenDb: ensureSharedTagOpsBackfilledInOpenDb,
  ensureSharedTagOpsReplayedInOpenDb: ensureSharedTagOpsReplayedInOpenDb,
  readSharedTagOpsDiagnosticsInOpenDb: readSharedTagOpsDiagnosticsInOpenDb,
  readSharedTagOpsConflictReportInOpenDb: readSharedTagOpsConflictReportInOpenDb,
  readSharedMetadataMigrationDiagnosticsInOpenDb: readSharedMetadataMigrationDiagnosticsInOpenDb,
  repairSharedMetadataInOpenDb: repairSharedMetadataInOpenDb,
  backupsRootPath: backupsRootPath,
  maintenanceStatePath: maintenanceStatePath,
  dataRoot: dataRoot,
  librarySqlitePath: librarySqlitePath,
  previewSqlitePath: previewSqlitePath,
  kvsSqlitePath: kvsSqlitePath,
  eventsSqlitePath: eventsSqlitePath,
  hashSqlitePath: hashSqlitePath,
  metricsSqlitePath: metricsSqlitePath,
  openLibraryDb: openLibraryDb,
  openPreviewDb: openPreviewDb,
  openKvsDb: openKvsDb,
  openEventsDb: openEventsDb,
  openHashDb: openHashDb,
  openMetricsDb: openMetricsDb,
  closeLibraryDb: closeLibraryDb,
  closePreviewDb: closePreviewDb,
  closeCacheDb: closeCacheDb,
  checkpointOpenCacheDbs: checkpointOpenCacheDbs,
  getOpenPreviewDb: getOpenPreviewDb,
  loadLibraryShell: loadLibraryShell,
  localPreviewImageDir: localPreviewImageDir,
  rootPreviewImageDir: rootPreviewImageDir,
  rootCacheDir: rootCacheDir,
  rootIndexDbPath: rootIndexDbPath,
  legacyRootPreviewCacheDir: legacyRootPreviewCacheDir,
  fallbackPreviewImageDir: fallbackPreviewImageDir,
  restoreLatestDatabaseBackupForLabel: restoreLatestDatabaseBackupForLabel,
  quarantineSqliteFiles: quarantineSqliteFiles,
  recoveryMessage: recoveryMessage,
  inspectRootIndexSnapshotMaintenance: inspectRootIndexSnapshotMaintenance,
  cleanupRootIndexSnapshotMaintenance: cleanupRootIndexSnapshotMaintenance,
  dataPath: dataPath,
  nodeRequire: nodeRequire,
  storageProfileForPath: storageProfileForPath,
  scanWorkerCount: scanWorkerCount,
  emitFontIndexProgress: emitFontIndexProgress,
  recheckGlobalIoQueues: recheckGlobalIoQueues,
  globalIoSnapshot: globalIoSnapshot,
  cacheKeyForRootFile: cacheKeyForRootFile,
  cacheEntryRuntimePath: cacheEntryRuntimePath,
  sanitizeCachedFont: sanitizeCachedFont,
  cachedFontForRuntime: cachedFontForRuntime,
  ensureRootScanCacheStorage: ensureRootScanCacheStorage,
  loadLegacyScanCache: loadLegacyScanCache,
  saveScanCacheFile: saveScanCacheFile,
  writeRootCacheManifest: writeRootCacheManifest,
  openRootIndexDb: openRootIndexDb,
  withRootCacheWriteLock: withRootCacheWriteLock,
  saveRootIndexSqliteChanges: saveRootIndexSqliteChanges,
  upsertFontHashIndex: upsertFontHashIndex,
  recordCacheEvent: recordCacheEvent,
  invalidateSharedFontRuntimeCaches: invalidateSharedFontRuntimeCaches,
  createFontScanJobId: createFontScanJobId,
  rootIndexDbDir: rootIndexDbDir,
  rootCacheLockDir: rootCacheLockDir,
  resolveActiveRootIndexDbPath: resolveActiveRootIndexDbPath,
  sqliteQuickCheck: sqliteQuickCheck,
  hideDirectoryOnWindows: hideDirectoryOnWindows,
  initializeRootEventsDb: initializeRootEventsDb,
  initializeRootHashDb: initializeRootHashDb,
  initializeRootMetricsDb: initializeRootMetricsDb,
  rootEventsDbPath: rootEventsDbPath,
  rootHashDbPath: rootHashDbPath,
  rootMetricsDbPath: rootMetricsDbPath,
  openStableSqliteDb: openStableSqliteDb,
  initializePreviewDb: initializePreviewDb,
  writeRootPreviewCacheManifest: writeRootPreviewCacheManifest,
  rootPreviewCacheDir: rootPreviewCacheDir,
  rootPreviewDbPath: rootPreviewDbPath,
  syncMergedIndexForRootIncremental: syncMergedIndexForRootIncremental,
  isIgnoredWatcherPath: isIgnoredWatcherPath,
});
const {
  scanFoldersManaged,
  cancelActiveFontScan,
  activeFontScanStatus,
  startWatchingFolders,
  refreshWatchedFolder,
  readSharedMetadataFrontendDiagnostics,
  repairSharedMetadataFromFrontend,
  readSharedIndexSnapshotFrontendDiagnostics,
  repairSharedIndexSnapshotFromFrontend,
  runDatabaseHealthCheck,
  createDatabaseBackup,
  runDatabaseMaintenance,
  restoreLatestApplicationDatabase,
  listBackgroundTaskSummaries,
  runBackgroundTaskSchedulerOnce,
  backgroundTaskSchedulerStatus,
  compareFontInstalled,
  compareFontsInstalled,
  refreshInstallStatusIndex,
  startInstallStatusRefreshIndex
} = operationsComposition.capabilities;
const {
  runStartupDatabaseMaintenance,
  startBackgroundTaskScheduler,
  stopBackgroundTaskScheduler,
  stopFolderWatchers
} = operationsComposition.lifecycle;
feedback.bindOperations(operationsComposition.feedback);
feedback.assertReady();
operationsComposition.startStartupTasks();

registerMainProcessRuntime(
  createMainRuntimeRegistrationPayload({
    appName: APP_NAME,
    appId: APP_ID,
    buildMarker: BUILD_MARKER,
    logSchemaVersion: LOG_SCHEMA_VERSION,
    cacheArchitectureVersion: CACHE_ARCHITECTURE_VERSION,
    watcherStartupGraceMs: WATCHER_STARTUP_GRACE_MS,
    editionLogLine: "edition v3.0.0 stable release",
    scanTuningLogLine: `scan tuning: cpu=${CPU_COUNT} localWorkers=${LOCAL_SCAN_WORKERS} networkWorkers=${NETWORK_SCAN_WORKERS} workerBatch=${SCAN_WORKER_BATCH_SIZE} statConcurrency=${SCAN_STAT_CONCURRENCY} storageMediaDetect=${WINDOWS_STORAGE_MEDIA_DETECT_ENABLED ? "on" : "off"}`,
    beginStartupSessionSync,
    ensureDataRootSync,
    migrateLegacyUserDataIfNeeded,
    initializeCacheArchitecture: initializeCacheArchitectureV2,
    diagnoseRustCoreWorker: rustCoreWorkerRuntime.diagnoseRustCoreWorker,
    dataRoot,
    dataRootErrorMessage,
    showExistingWindow,
    requestRendererWindowsCloseForQuit,
    logPath,
    ioLaneSummary,
    cleanupTemporaryActiveFontsUntilEmpty,
    flushPendingTemporaryFontDeletes,
    runStartupCriticalSchemaAudit: dataComposition.lifecycle.runStartupCriticalSchemaAudit,
    registerFontProtocol,
    startPerformanceLogSampler,
    stopPerformanceLogSampler,
    flushPerformanceLogs,
    createWindow,
    runStartupDatabaseMaintenance,
    startupDbMaintenanceIdleDelayMs: STARTUP_DB_MAINTENANCE_IDLE_DELAY_MS,
    startupBackgroundTasksEnabled: STARTUP_BACKGROUND_TASKS_ENABLED,
    startBackgroundTaskScheduler,
    stopBackgroundTaskScheduler,
    stopFolderWatchers,
    flushActivationInstallStatusSave,
    hasPendingActivationInstallStatusSave,
    hasInFlightActivationInstallStatusSave,
    setCacheKvs,
    dbQueryWorkerShutdown: dataComposition.lifecycle.dbQueryWorkerShutdown,
    stopRustCoreDaemon: rustCoreWorkerRuntime.stopRustCoreDaemon,
    markCleanShutdownSync,
    flushStartupLogAsync,
    flushStartupLogSync,
    appendStartupLog,
    assertFeatureForChannel: coreComposition.capabilities.assertFeatureForChannel,
    getLicenseStatus: coreComposition.capabilities.getLicenseStatus,
    reportPerformanceEvent,
    loadLibrary,
    loadLibraryShell,
    saveLibrary,
    scanFoldersManaged,
    cancelActiveFontScan,
    activeFontScanStatus,
    loadFolderCache,
    searchFontsInLibrary,
    queryFontsInLibrary,
    queryFontPageInLibrary,
    checkSharedMetadataUpdates: dataComposition.capabilities.checkSharedMetadataUpdates,
    getFontMetricsFromLibrary,
    startWatchingFolders,
    refreshWatchedFolder,
    getCacheStats,
    cacheArchitectureInfo,
    getMigrationDiagnostics: () => migrationDiagnosticsRuntime.snapshot(),
    clearMigrationDiagnostics: () => migrationDiagnosticsRuntime.clear(),
    readSharedMetadataFrontendDiagnostics,
    repairSharedMetadataFromFrontend,
    clearScanCache,
    clearPreviewCache,
    runDatabaseHealthCheck,
    createDatabaseBackup,
    runDatabaseMaintenance,
    readSharedIndexSnapshotFrontendDiagnostics,
    repairSharedIndexSnapshotFromFrontend,
    restoreLatestApplicationDatabase,
    listBackgroundTaskSummaries,
    runBackgroundTaskSchedulerOnce,
    backgroundTaskSchedulerStatus,
    markRendererUserActivity,
    reportRendererLongTask,
    getSystemInstalledFonts,
    scanSystemInstalledFonts,
    compareFontInstalled,
    compareFontsInstalled,
    refreshInstallStatusIndex,
    startInstallStatusRefreshIndex,
    getInstallStatusIndexSnapshot,
    installFontSystemWide,
    uninstallFontSystemWide,
    deleteFontFilesToTrash,
    setFontDeleteProtectionInIndex,
    setSharedFontFavoriteInIndex,
    setLocalFontTags,
    setLocalFontTagsBatch,
    deleteLocalFontTag,
    setSharedFontTagsInIndex,
    setSharedFontTagsBatchInIndex,
    renameSharedFontTagInIndex,
    deleteSharedFontTagInIndex,
    activateFontSession,
    activateFontSessionsBatch,
    deactivateFontSession,
    deactivateFontSessionsBatch,
    installFontForCurrentUser,
    uninstallManagedFont,
    readPreviewFontData,
    renderFontPreviewImage,
    readCachedFontPreviewImage,
    readCachedFontPreviewImages,
    ensureFontPreviewCache,
    getPreviewCacheStatus,
    createPhysicalFolder,
    renamePhysicalFolder,
    listPhysicalFolderTree,
    moveFontFileToFolder,
    moveFontFilesToFolder,
  }),
);
