import type {
  MainApplicationRuntime, MainCoreCompositionRuntime, MainDataCompositionRuntime,
  MainMutationCompositionRuntime, MainOperationsCompositionRuntime, MainApplicationRegistrationGroups,
} from './mainCompositionContracts';
import { createMainRuntimeRegistrationPayload } from './mainRuntimeRegistrationPayload';

export interface MainApplicationOptions {
  core: Pick<MainCoreCompositionRuntime, 'capabilities' | 'lifecycle'>;
  data: Pick<MainDataCompositionRuntime, 'capabilities' | 'lifecycle'>;
  mutation: Pick<MainMutationCompositionRuntime, 'capabilities' | 'lifecycle'>;
  operations: Pick<MainOperationsCompositionRuntime, 'capabilities' | 'lifecycle'>;
}

// No resource ownership or startup work: publish only the registered capabilities.
export function createMainApplicationRuntime({ core, data, mutation, operations }: MainApplicationOptions): MainApplicationRuntime {
  const groups: MainApplicationRegistrationGroups = {
    lifecycle: {
      appendStartupLog: core.capabilities.appendStartupLog,
      appName: core.capabilities.appName,
      appId: core.capabilities.appId,
      buildMarker: core.capabilities.buildMarker,
      logSchemaVersion: core.capabilities.logSchemaVersion,
      cacheArchitectureVersion: core.capabilities.cacheArchitectureVersion,
      watcherStartupGraceMs: core.capabilities.watcherStartupGraceMs,
      editionLogLine: core.capabilities.editionLogLine,
      scanTuningLogLine: core.capabilities.scanTuningLogLine,
      dataRoot: core.capabilities.dataRoot,
      dataRootErrorMessage: core.capabilities.dataRootErrorMessage,
      showExistingWindow: core.capabilities.showExistingWindow,
      logPath: core.capabilities.logPath,
      ioLaneSummary: core.capabilities.ioLaneSummary,
      registerFontProtocol: core.capabilities.registerFontProtocol,
      createWindow: core.capabilities.createWindow,
      beginStartupSessionSync: core.lifecycle.beginStartupSessionSync,
      ensureDataRootSync: core.lifecycle.ensureDataRootSync,
      migrateLegacyUserDataIfNeeded: core.lifecycle.migrateLegacyUserDataIfNeeded,
      diagnoseRustCoreWorker: core.lifecycle.diagnoseRustCoreWorker,
      requestRendererWindowsCloseForQuit: core.lifecycle.requestRendererWindowsCloseForQuit,
      startPerformanceLogSampler: core.lifecycle.startPerformanceLogSampler,
      stopPerformanceLogSampler: core.lifecycle.stopPerformanceLogSampler,
      flushPerformanceLogs: core.lifecycle.flushPerformanceLogs,
      stopRustCoreDaemon: core.lifecycle.stopRustCoreDaemon,
      markCleanShutdownSync: core.lifecycle.markCleanShutdownSync,
      flushStartupLogAsync: core.lifecycle.flushStartupLogAsync,
      flushStartupLogSync: core.lifecycle.flushStartupLogSync,
      setCacheKvs: data.capabilities.setCacheKvs,
      initializeCacheArchitecture: data.lifecycle.initializeCacheArchitecture,
      runStartupCriticalSchemaAudit: data.lifecycle.runStartupCriticalSchemaAudit,
      dbQueryWorkerShutdown: data.lifecycle.dbQueryWorkerShutdown,
      cleanupTemporaryActiveFontsUntilEmpty: mutation.lifecycle.cleanupTemporaryActiveFontsUntilEmpty,
      flushPendingTemporaryFontDeletes: mutation.lifecycle.flushPendingTemporaryFontDeletes,
      flushActivationInstallStatusSave: mutation.lifecycle.flushActivationInstallStatusSave,
      hasPendingActivationInstallStatusSave: mutation.lifecycle.hasPendingActivationInstallStatusSave,
      hasInFlightActivationInstallStatusSave: mutation.lifecycle.hasInFlightActivationInstallStatusSave,
      startupDbMaintenanceIdleDelayMs: operations.capabilities.startupDbMaintenanceIdleDelayMs,
      startupBackgroundTasksEnabled: operations.capabilities.startupBackgroundTasksEnabled,
      runStartupDatabaseMaintenance: operations.lifecycle.runStartupDatabaseMaintenance,
      startBackgroundTaskScheduler: operations.lifecycle.startBackgroundTaskScheduler,
      stopBackgroundTaskScheduler: operations.lifecycle.stopBackgroundTaskScheduler,
      stopFolderWatchers: operations.lifecycle.stopFolderWatchers,
    },
    query: {
      reportPerformanceEvent: core.capabilities.reportPerformanceEvent,
      assertFeatureForChannel: core.capabilities.assertFeatureForChannel,
      getLicenseStatus: core.capabilities.getLicenseStatus,
      markRendererUserActivity: core.capabilities.markRendererUserActivity,
      reportRendererLongTask: core.capabilities.reportRendererLongTask,
      loadLibrary: data.capabilities.loadLibrary,
      loadLibraryShell: data.capabilities.loadLibraryShell,
      loadFolderCache: data.capabilities.loadFolderCache,
      searchFontsInLibrary: data.capabilities.searchFontsInLibrary,
      queryFontsInLibrary: data.capabilities.queryFontsInLibrary,
      queryFontPageInLibrary: data.capabilities.queryFontPageInLibrary,
      checkSharedMetadataUpdates: data.capabilities.checkSharedMetadataUpdates,
      getFontMetricsFromLibrary: data.capabilities.getFontMetricsFromLibrary,
      getSystemInstalledFonts: data.capabilities.getSystemInstalledFonts,
      scanSystemInstalledFonts: data.capabilities.scanSystemInstalledFonts,
      getInstallStatusIndexSnapshot: data.capabilities.getInstallStatusIndexSnapshot,
      listPhysicalFolderTree: data.capabilities.listPhysicalFolderTree,
      activeFontScanStatus: operations.capabilities.activeFontScanStatus,
      compareFontInstalled: operations.capabilities.compareFontInstalled,
      compareFontsInstalled: operations.capabilities.compareFontsInstalled,
    },
    mutation: {
      saveLibrary: mutation.capabilities.saveLibrary,
      installFontSystemWide: mutation.capabilities.installFontSystemWide,
      uninstallFontSystemWide: mutation.capabilities.uninstallFontSystemWide,
      deleteFontFilesToTrash: mutation.capabilities.deleteFontFilesToTrash,
      setFontDeleteProtectionInIndex: mutation.capabilities.setFontDeleteProtectionInIndex,
      setSharedFontFavoriteInIndex: mutation.capabilities.setSharedFontFavoriteInIndex,
      setLocalFontTags: mutation.capabilities.setLocalFontTags,
      setLocalFontTagsBatch: mutation.capabilities.setLocalFontTagsBatch,
      deleteLocalFontTag: mutation.capabilities.deleteLocalFontTag,
      setSharedFontTagsInIndex: mutation.capabilities.setSharedFontTagsInIndex,
      setSharedFontTagsBatchInIndex: mutation.capabilities.setSharedFontTagsBatchInIndex,
      renameSharedFontTagInIndex: mutation.capabilities.renameSharedFontTagInIndex,
      deleteSharedFontTagInIndex: mutation.capabilities.deleteSharedFontTagInIndex,
      activateFontSession: mutation.capabilities.activateFontSession,
      activateFontSessionsBatch: mutation.capabilities.activateFontSessionsBatch,
      deactivateFontSession: mutation.capabilities.deactivateFontSession,
      deactivateFontSessionsBatch: mutation.capabilities.deactivateFontSessionsBatch,
      installFontForCurrentUser: mutation.capabilities.installFontForCurrentUser,
      uninstallManagedFont: mutation.capabilities.uninstallManagedFont,
      createPhysicalFolder: mutation.capabilities.createPhysicalFolder,
      renamePhysicalFolder: mutation.capabilities.renamePhysicalFolder,
      moveFontFileToFolder: mutation.capabilities.moveFontFileToFolder,
      moveFontFilesToFolder: mutation.capabilities.moveFontFilesToFolder,
      scanFoldersManaged: operations.capabilities.scanFoldersManaged,
      cancelActiveFontScan: operations.capabilities.cancelActiveFontScan,
      startWatchingFolders: operations.capabilities.startWatchingFolders,
      refreshWatchedFolder: operations.capabilities.refreshWatchedFolder,
      refreshInstallStatusIndex: operations.capabilities.refreshInstallStatusIndex,
      startInstallStatusRefreshIndex: operations.capabilities.startInstallStatusRefreshIndex,
    },
    maintenance: {
      getMigrationDiagnostics: core.capabilities.getMigrationDiagnostics,
      clearMigrationDiagnostics: core.capabilities.clearMigrationDiagnostics,
      getCacheStats: data.capabilities.getCacheStats,
      cacheArchitectureInfo: data.capabilities.cacheArchitectureInfo,
      clearScanCache: data.capabilities.clearScanCache,
      clearPreviewCache: data.capabilities.clearPreviewCache,
      readSharedMetadataFrontendDiagnostics: operations.capabilities.readSharedMetadataFrontendDiagnostics,
      repairSharedMetadataFromFrontend: operations.capabilities.repairSharedMetadataFromFrontend,
      readSharedIndexSnapshotFrontendDiagnostics: operations.capabilities.readSharedIndexSnapshotFrontendDiagnostics,
      repairSharedIndexSnapshotFromFrontend: operations.capabilities.repairSharedIndexSnapshotFromFrontend,
      runDatabaseHealthCheck: operations.capabilities.runDatabaseHealthCheck,
      createDatabaseBackup: operations.capabilities.createDatabaseBackup,
      runDatabaseMaintenance: operations.capabilities.runDatabaseMaintenance,
      restoreLatestApplicationDatabase: operations.capabilities.restoreLatestApplicationDatabase,
      listBackgroundTaskSummaries: operations.capabilities.listBackgroundTaskSummaries,
      runBackgroundTaskSchedulerOnce: operations.capabilities.runBackgroundTaskSchedulerOnce,
      backgroundTaskSchedulerStatus: operations.capabilities.backgroundTaskSchedulerStatus,
    },
    preview: {
      readPreviewFontData: data.capabilities.readPreviewFontData,
      renderFontPreviewImage: data.capabilities.renderFontPreviewImage,
      readCachedFontPreviewImage: data.capabilities.readCachedFontPreviewImage,
      readCachedFontPreviewImages: data.capabilities.readCachedFontPreviewImages,
      ensureFontPreviewCache: data.capabilities.ensureFontPreviewCache,
      getPreviewCacheStatus: data.capabilities.getPreviewCacheStatus,
    },
  };
  return { registration: createMainRuntimeRegistrationPayload(groups) };
}
