import { createRustIndexingClientRuntime } from './clients/rustIndexingClientRuntime'
import { createRustMetadataClientRuntime } from './clients/rustMetadataClientRuntime'
import { createRustWindowsClientRuntime } from './clients/rustWindowsClientRuntime'
import { createRustPreviewClientRuntime } from './clients/rustPreviewClientRuntime'
import { createRustMaintenanceClientRuntime } from './clients/rustMaintenanceClientRuntime'
import { createRustCoreWorkerTransportRuntime } from './rustCoreWorkerTransportRuntime'

import type { RustCoreWorkerRuntimeOptions } from './rustCoreWorkerContracts'

// Preserve the existing public type import path without loading another runtime.
export type {
  RustCoreWorkerStatus,
  RustFontScriptHint,
  RustFontStyleHint,
  RustFontFamilyHint,
  RustFontNameHint,
  RustListedFontFile,
  RustListedDirectory,
  RustFontIndexListResult,
  RustFontParseBatchResult,
  RustRootIndexApplyChangesInput,
  RustRootIndexApplyChangesResult,
  RustMergedIndexPageQueryInput,
  RustMergedIndexPageQueryResult,
  RustMergedIndexIdsQueryInput,
  RustMergedIndexIdsQueryResult,
  RustMergedIndexMetricsQueryInput,
  RustMergedIndexMetricsQueryResult,
  RustMergedIndexMutationProtocol,
  RustMergedIndexRebuildSource,
  RustMergedIndexRebuildInput,
  RustMergedIndexRebuildResult,
  RustMergedIndexSyncInput,
  RustMergedIndexSyncResult,
  RustSystemInstalledFontsInput,
  RustSystemInstalledFontsResult,
  RustWatcherPreflightInput,
  RustWatcherPreflightResult,
  RustInstallStatusReadResult,
  RustInstallStatusSaveResult,
  RustInstallStatusCompareInput,
  RustInstallStatusCompareResult,
  RustLocalTagsSetRow,
  RustLocalTagsReadRow,
  RustLocalTagsReadInput,
  RustLocalTagsReadResult,
  RustLocalTagsSetInput,
  RustLocalTagsDeleteTagInput,
  RustLocalTagsMutationStateSignal,
  RustLocalTagsSetResult,
  RustLocalTagsDeleteTagResult,
  RustSharedMetadataApplyRow,
  RustSharedMetadataApplyInput,
  RustSharedMetadataMutationStateSignal,
  RustTagMutationProtocolResult,
  RustSharedMetadataApplyResult,
  RustSharedMetadataRemoveTagInput,
  RustSharedMetadataRemoveTagResult,
  RustSharedMetadataSignatureInput,
  RustSharedMetadataKnownTagsInput,
  RustSharedMetadataKnownTagsResult,
  RustSharedMetadataOverlayReadEntry,
  RustSharedMetadataOverlayReadInput,
  RustSharedMetadataOverlayMatchedEntry,
  RustSharedMetadataOverlayReadResult,
  RustSharedMetadataSignatureResult,
  RustPreviewCacheReadStatusInput,
  RustPreviewCacheReadStatusResult,
  RustPreviewCacheApplyInput,
  RustPreviewCacheApplyResult,
  RustPreviewCacheDeleteInput,
  RustPreviewCacheDeleteResult,
  RustPreviewCacheQueryRow,
  RustPreviewCacheQueryInput,
  RustPreviewCacheQueryMatch,
  RustPreviewCacheQueryResult,
  RustPreviewCacheTouchInput,
  RustPreviewCacheTouchResult,
  RustPreviewCacheBatchInput,
  RustPreviewCacheBatchMatch,
  RustPreviewCacheBatchResult,
  RustPreviewCacheMaintenanceInput,
  RustPreviewCacheMaintenanceResult,
  RustPhysicalFolderTreeInput,
  RustPhysicalFolderTreeResult,
  RustFontActivationFileCopy,
  RustFontActivationFilesInput,
  RustFontActivationFilesResult,
  RustDatabaseMaintenanceFileItem,
  RustDatabaseHealthCheckInput,
  RustDatabaseHealthCheckResult,
  RustDatabaseBackupInput,
  RustDatabaseBackupResult,
  RustFontResourceBatchEntry,
  RustFontResourceBatchResult,
  RustFontRegistryResult,
  RustFontNotifyResult,
  RustPreviewRenderImageInput,
  RustPreviewRenderImageResult,
  RustCoreWorkerRuntimeOptions,
} from './rustCoreWorkerContracts'

export function createRustCoreWorkerRuntime(options: RustCoreWorkerRuntimeOptions) {
  const transport = createRustCoreWorkerTransportRuntime(options)
  const indexingClient = createRustIndexingClientRuntime({
    diagnoseRustCoreWorker: transport.diagnoseRustCoreWorker,
    runRustCoreScheduledCommand: transport.runRustCoreScheduledCommand,
    createTemporaryJsonFile: transport.createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })
  const metadataClient = createRustMetadataClientRuntime({
    diagnoseRustCoreWorker: transport.diagnoseRustCoreWorker,
    runRustCoreScheduledCommand: transport.runRustCoreScheduledCommand,
    createTemporaryJsonFile: transport.createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })
  const windowsClient = createRustWindowsClientRuntime({
    diagnoseRustCoreWorker: transport.diagnoseRustCoreWorker,
    runRustCoreScheduledCommand: transport.runRustCoreScheduledCommand,
    createTemporaryJsonFile: transport.createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })
  const previewClient = createRustPreviewClientRuntime({
    diagnoseRustCoreWorker: transport.diagnoseRustCoreWorker,
    runRustCoreScheduledCommand: transport.runRustCoreScheduledCommand,
    createTemporaryJsonFile: transport.createTemporaryJsonFile,
    appendPreviewCacheFailureLog: transport.appendPreviewCacheFailureLog,
    appendStartupLog: options.appendStartupLog,
  })
  const maintenanceClient = createRustMaintenanceClientRuntime({
    diagnoseRustCoreWorker: transport.diagnoseRustCoreWorker,
    runRustCoreScheduledCommand: transport.runRustCoreScheduledCommand,
    createTemporaryJsonFile: transport.createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })

  // Publish original function references; state and behavior stay with their owners.
  return {
    diagnoseRustCoreWorker: transport.diagnoseRustCoreWorker,
    rustCoreWorkerStatus: transport.rustCoreWorkerStatus,
    invalidateRustCoreSchedulerCaches: transport.invalidateRustCoreSchedulerCaches,
    cancelRustCoreSchedulerScopes: transport.cancelRustCoreSchedulerScopes,
    noteRustCoreSchedulerInteractiveActivity: transport.noteRustCoreSchedulerInteractiveActivity,
    rustCoreDaemonStatus: transport.rustCoreDaemonStatus,
    stopRustCoreDaemon: transport.stopRustCoreDaemon,
    runRustFontIndexListWorker: indexingClient.runRustFontIndexListWorker,
    runRustFontParseBatch: indexingClient.runRustFontParseBatch,
    runRustRootIndexApplyChanges: indexingClient.runRustRootIndexApplyChanges,
    runRustMergedIndexPageQuery: indexingClient.runRustMergedIndexPageQuery,
    runRustMergedIndexIdsQuery: indexingClient.runRustMergedIndexIdsQuery,
    runRustMergedIndexMetricsQuery: indexingClient.runRustMergedIndexMetricsQuery,
    runRustMergedIndexRebuild: indexingClient.runRustMergedIndexRebuild,
    runRustMergedIndexSync: indexingClient.runRustMergedIndexSync,
    runRustWatcherPreflight: indexingClient.runRustWatcherPreflight,
    runRustInstallStatusRead: metadataClient.runRustInstallStatusRead,
    runRustInstallStatusSave: metadataClient.runRustInstallStatusSave,
    runRustInstallStatusCompare: metadataClient.runRustInstallStatusCompare,
    runRustLocalTagsRead: metadataClient.runRustLocalTagsRead,
    runRustLocalTagsSet: metadataClient.runRustLocalTagsSet,
    runRustLocalTagsDeleteTag: metadataClient.runRustLocalTagsDeleteTag,
    runRustSharedMetadataApply: metadataClient.runRustSharedMetadataApply,
    runRustSharedMetadataRemoveTag: metadataClient.runRustSharedMetadataRemoveTag,
    runRustSharedMetadataKnownTags: metadataClient.runRustSharedMetadataKnownTags,
    runRustSharedMetadataOverlayRead: metadataClient.runRustSharedMetadataOverlayRead,
    runRustSharedMetadataSignature: metadataClient.runRustSharedMetadataSignature,
    runRustPreviewCacheReadStatus: previewClient.runRustPreviewCacheReadStatus,
    runRustPreviewCacheApply: previewClient.runRustPreviewCacheApply,
    runRustPreviewCacheDelete: previewClient.runRustPreviewCacheDelete,
    runRustPreviewCacheQuery: previewClient.runRustPreviewCacheQuery,
    runRustPreviewCacheTouch: previewClient.runRustPreviewCacheTouch,
    runRustPreviewCacheBatch: previewClient.runRustPreviewCacheBatch,
    runRustPreviewCacheMaintenance: previewClient.runRustPreviewCacheMaintenance,
    runRustDatabaseHealthCheck: maintenanceClient.runRustDatabaseHealthCheck,
    runRustDatabaseBackup: maintenanceClient.runRustDatabaseBackup,
    runRustFontResourceAdd: windowsClient.runRustFontResourceAdd,
    runRustFontResourceRemove: windowsClient.runRustFontResourceRemove,
    runRustFontRegistryApply: windowsClient.runRustFontRegistryApply,
    runRustFontRegistryDelete: windowsClient.runRustFontRegistryDelete,
    runRustFontChangeNotify: windowsClient.runRustFontChangeNotify,
    runRustPhysicalFolderTree: windowsClient.runRustPhysicalFolderTree,
    runRustFontActivationFiles: windowsClient.runRustFontActivationFiles,
    runRustPreviewRenderImage: previewClient.runRustPreviewRenderImage,
    runRustSystemInstalledFonts: windowsClient.runRustSystemInstalledFonts,
  }
}
