import { createRustIndexingClientRuntime } from './clients/rustIndexingClientRuntime'
import { createRustMetadataClientRuntime } from './clients/rustMetadataClientRuntime'
import { createRustWindowsClientRuntime } from './clients/rustWindowsClientRuntime'
import { createRustPreviewClientRuntime } from './clients/rustPreviewClientRuntime'
import { createRustMaintenanceClientRuntime } from './clients/rustMaintenanceClientRuntime'
import { createRustCoreWorkerTransportRuntime } from './rustCoreWorkerTransportRuntime'

import type { RustCoreWorkerRuntimeOptions } from './rustCoreWorkerContracts'

// Preserve the existing public type import path without loading another runtime.
export type {
  RustCoreWorkerStatus,
  RustFontScriptHint,
  RustFontStyleHint,
  RustFontFamilyHint,
  RustFontNameHint,
  RustListedFontFile,
  RustListedDirectory,
  RustFontIndexListResult,
  RustFontParseBatchResult,
  RustRootIndexApplyChangesInput,
  RustRootIndexApplyChangesResult,
  RustMergedIndexPageQueryInput,
  RustMergedIndexPageQueryResult,
  RustMergedIndexIdsQueryInput,
  RustMergedIndexIdsQueryResult,
  RustMergedIndexMetricsQueryInput,
  RustMergedIndexMetricsQueryResult,
  RustMergedIndexMutationProtocol,
  RustMergedIndexRebuildSource,
  RustMergedIndexRebuildInput,
  RustMergedIndexRebuildResult,
  RustMergedIndexSyncInput,
  RustMergedIndexSyncResult,
  RustSystemInstalledFontsInput,
  RustSystemInstalledFontsResult,
  RustWatcherPreflightInput,
  RustWatcherPreflightResult,
  RustInstallStatusReadResult,
  RustInstallStatusSaveResult,
  RustInstallStatusCompareInput,
  RustInstallStatusCompareResult,
  RustLocalTagsSetRow,
  RustLocalTagsReadRow,
  RustLocalTagsReadInput,
  RustLocalTagsReadResult,
  RustLocalTagsSetInput,
  RustLocalTagsDeleteTagInput,
  RustLocalTagsMutationStateSignal,
  RustLocalTagsSetResult,
  RustLocalTagsDeleteTagResult,
  RustSharedMetadataApplyRow,
  RustSharedMetadataApplyInput,
  RustSharedMetadataMutationStateSignal,
  RustTagMutationProtocolResult,
  RustSharedMetadataApplyResult,
  RustSharedMetadataRemoveTagInput,
  RustSharedMetadataRemoveTagResult,
  RustSharedMetadataSignatureInput,
  RustSharedMetadataKnownTagsInput,
  RustSharedMetadataKnownTagsResult,
  RustSharedMetadataOverlayReadEntry,
  RustSharedMetadataOverlayReadInput,
  RustSharedMetadataOverlayMatchedEntry,
  RustSharedMetadataOverlayReadResult,
  RustSharedMetadataSignatureResult,
  RustPreviewCacheReadStatusInput,
  RustPreviewCacheReadStatusResult,
  RustPreviewCacheApplyInput,
  RustPreviewCacheApplyResult,
  RustPreviewCacheDeleteInput,
  RustPreviewCacheDeleteResult,
  RustPreviewCacheQueryRow,
  RustPreviewCacheQueryInput,
  RustPreviewCacheQueryMatch,
  RustPreviewCacheQueryResult,
  RustPreviewCacheTouchInput,
  RustPreviewCacheTouchResult,
  RustPreviewCacheBatchInput,
  RustPreviewCacheBatchMatch,
  RustPreviewCacheBatchResult,
  RustPreviewCacheMaintenanceInput,
  RustPreviewCacheMaintenanceResult,
  RustPhysicalFolderTreeInput,
  RustPhysicalFolderTreeResult,
  RustFontActivationFileCopy,
  RustFontActivationFilesInput,
  RustFontActivationFilesResult,
  RustDatabaseMaintenanceFileItem,
  RustDatabaseHealthCheckInput,
  RustDatabaseHealthCheckResult,
  RustDatabaseBackupInput,
  RustDatabaseBackupResult,
  RustFontResourceBatchEntry,
  RustFontResourceBatchResult,
  RustFontRegistryResult,
  RustFontNotifyResult,
  RustPreviewRenderImageInput,
  RustPreviewRenderImageResult,
  RustCoreWorkerRuntimeOptions,
} from './rustCoreWorkerContracts'

export function createRustCoreWorkerRuntime(options: RustCoreWorkerRuntimeOptions) {
  const transport = createRustCoreWorkerTransportRuntime(options)
  const {
    diagnoseRustCoreWorker,
    invalidateRustCoreSchedulerCaches, cancelRustCoreSchedulerScopes,
    noteRustCoreSchedulerInteractiveActivity, runRustCoreScheduledCommand,
    appendPreviewCacheFailureLog, createTemporaryJsonFile,
  } = transport
  const {
    runRustFontIndexListWorker,
    runRustFontParseBatch,
    runRustRootIndexApplyChanges,
    runRustMergedIndexPageQuery,
    runRustMergedIndexIdsQuery,
    runRustMergedIndexMetricsQuery,
    runRustMergedIndexRebuild,
    runRustMergedIndexSync,
    runRustWatcherPreflight,
  } = createRustIndexingClientRuntime({
    diagnoseRustCoreWorker, runRustCoreScheduledCommand, createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })
  const {
    runRustInstallStatusRead,
    runRustInstallStatusSave,
    runRustInstallStatusCompare,
    runRustLocalTagsRead,
    runRustLocalTagsSet,
    runRustLocalTagsDeleteTag,
    runRustSharedMetadataApply,
    runRustSharedMetadataRemoveTag,
    runRustSharedMetadataKnownTags,
    runRustSharedMetadataOverlayRead,
    runRustSharedMetadataSignature,
  } = createRustMetadataClientRuntime({
    diagnoseRustCoreWorker, runRustCoreScheduledCommand, createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })
  const {
    runRustFontResourceAdd,
    runRustFontResourceRemove,
    runRustFontRegistryApply,
    runRustFontRegistryDelete,
    runRustFontChangeNotify,
    runRustPhysicalFolderTree,
    runRustFontActivationFiles,
    runRustSystemInstalledFonts,
  } = createRustWindowsClientRuntime({
    diagnoseRustCoreWorker, runRustCoreScheduledCommand, createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })
  const {
    runRustPreviewCacheReadStatus,
    runRustPreviewCacheApply,
    runRustPreviewCacheDelete,
    runRustPreviewCacheQuery,
    runRustPreviewCacheTouch,
    runRustPreviewCacheBatch,
    runRustPreviewCacheMaintenance,
    runRustPreviewRenderImage,
  } = createRustPreviewClientRuntime({
    diagnoseRustCoreWorker, runRustCoreScheduledCommand, createTemporaryJsonFile, appendPreviewCacheFailureLog,
    appendStartupLog: options.appendStartupLog,
  })
  const { runRustDatabaseHealthCheck, runRustDatabaseBackup } = createRustMaintenanceClientRuntime({
    diagnoseRustCoreWorker, runRustCoreScheduledCommand, createTemporaryJsonFile,
    appendStartupLog: options.appendStartupLog,
  })

  return {
    diagnoseRustCoreWorker,
    rustCoreWorkerStatus: transport.rustCoreWorkerStatus,
    invalidateRustCoreSchedulerCaches,
    cancelRustCoreSchedulerScopes,
    noteRustCoreSchedulerInteractiveActivity,
    rustCoreDaemonStatus: transport.rustCoreDaemonStatus,
    stopRustCoreDaemon: transport.stopRustCoreDaemon,
    runRustFontIndexListWorker,
    runRustFontParseBatch,
    runRustRootIndexApplyChanges,
    runRustMergedIndexPageQuery,
    runRustMergedIndexIdsQuery,
    runRustMergedIndexMetricsQuery,
    runRustMergedIndexRebuild,
    runRustMergedIndexSync,
    runRustWatcherPreflight,
    runRustInstallStatusRead,
    runRustInstallStatusSave,
    runRustInstallStatusCompare,
    runRustLocalTagsRead,
    runRustLocalTagsSet,
    runRustLocalTagsDeleteTag,
    runRustSharedMetadataApply,
    runRustSharedMetadataRemoveTag,
    runRustSharedMetadataKnownTags,
    runRustSharedMetadataOverlayRead,
    runRustSharedMetadataSignature,
    runRustPreviewCacheReadStatus,
    runRustPreviewCacheApply,
    runRustPreviewCacheDelete,
    runRustPreviewCacheQuery,
    runRustPreviewCacheTouch,
    runRustPreviewCacheBatch,
    runRustPreviewCacheMaintenance,
    runRustDatabaseHealthCheck,
    runRustDatabaseBackup,
    runRustFontResourceAdd,
    runRustFontResourceRemove,
    runRustFontRegistryApply,
    runRustFontRegistryDelete,
    runRustFontChangeNotify,
    runRustPhysicalFolderTree,
    runRustFontActivationFiles,
    runRustPreviewRenderImage,
    runRustSystemInstalledFonts,
  }
}
