use rusqlite::Connection;
use serde_json::{json, Value};
use std::{fs,path::PathBuf,process::{Command,Output},time::{SystemTime,UNIX_EPOCH}};
struct Fixture{dir:PathBuf,db:PathBuf}
impl Fixture{fn new()->Self{let dir=std::env::temp_dir().join(format!("hfm-root-replace-{}-{}",std::process::id(),SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()));fs::create_dir_all(&dir).unwrap();Self{db:dir.join("index.sqlite"),dir}}fn run(&self,command:&str,payload:Value)->Output{let input=self.dir.join(format!("{}.json",command.trim_start_matches("--")));fs::write(&input,serde_json::to_vec(&payload).unwrap()).unwrap();Command::new(env!("CARGO_BIN_EXE_hfm-core-worker")).arg(command).arg("--db").arg(&self.db).arg("--root").arg(&self.dir).arg("--storage").arg("root").arg("--input").arg(input).arg("--schema-version").arg("4").arg("--cache-version").arg("7").arg("--script-detection-version").arg("1").output().unwrap()}}
impl Drop for Fixture{fn drop(&mut self){let _=fs::remove_dir_all(&self.dir);}}
fn entry(id:&str)->Value{json!({"relativePath":format!("{id}.ttf"),"entry":{"cacheKey":id,"fileSize":10,"modifiedAt":1,"createdAt":1,"status":"ok","font":{"id":id,"path":format!("{id}.ttf"),"fileName":format!("{id}.ttf"),"format":"ttf"},"cachedAt":"2026-09-20T00:00:00Z"}})}
fn ids(db:&PathBuf)->Vec<String>{let conn=Connection::open(db).unwrap();let mut stmt=conn.prepare("SELECT relative_path FROM entries WHERE COALESCE(is_deleted,0)=0 AND status<>'deleted' ORDER BY relative_path").unwrap();stmt.query_map([],|r|r.get::<_,String>(0)).unwrap().map(Result::unwrap).collect()}
#[test]fn root_index_replace_is_atomic_and_incremental_delete_remains_supported(){let f=Fixture::new();let initial=f.run("--root-index-apply-changes",json!({"upserts":[entry("old")],"deletes":[]}));assert!(initial.status.success(),"{}",String::from_utf8_lossy(&initial.stdout));assert_eq!(ids(&f.db),vec!["old.ttf"]);let replace=f.run("--root-index-replace",json!({"upserts":[entry("a"),entry("b")],"deletes":[]}));assert!(replace.status.success(),"{}",String::from_utf8_lossy(&replace.stdout));let receipt:Value=serde_json::from_slice(&replace.stdout).unwrap();assert_eq!(receipt["ok"],true);assert_eq!(receipt["count"],2);assert_eq!(ids(&f.db),vec!["a.ttf","b.ttf"]);let conn=Connection::open(&f.db).unwrap();conn.execute_batch("CREATE TRIGGER fail_replace BEFORE DELETE ON entries BEGIN SELECT RAISE(ABORT, 'controlled replace failure'); END;").unwrap();drop(conn);let failed=f.run("--root-index-replace",json!({"upserts":[entry("c")],"deletes":[]}));assert!(!failed.status.success());assert_eq!(ids(&f.db),vec!["a.ttf","b.ttf"]);let conn=Connection::open(&f.db).unwrap();conn.execute_batch("DROP TRIGGER fail_replace;").unwrap();drop(conn);let delete=f.run("--root-index-apply-changes",json!({"upserts":[],"deletes":["a.ttf"]}));assert!(delete.status.success(),"{}",String::from_utf8_lossy(&delete.stdout));assert_eq!(ids(&f.db),vec!["b.ttf"]);}
