import { AppLayout } from './AppLayout'
import { AppOverlays } from './AppOverlays'
import { AppSidebar } from './AppSidebar'
import { AppTopbar } from './AppTopbar'
import { FontDetailPanel } from './FontDetailPanel'
import { FontListPanel } from './FontListPanel'

export function AppRootView(props: any): JSX.Element {
  const {
    IS_DEVELOPMENT,
    status,
    themeMode,
    setThemeMode,
    indexingActive,
    cacheMenuOpen,
    setCacheMenuOpen,
    rescan,
    cancelIndexing,
    rebuildScanCache,
    clearAllCacheAction,
    detailVisible,
    sidebarPage,
    setSidebarPage,
    activeFilter,
    setActiveFilter,
    advancedFilterCount,
    refreshDeveloperStatusDetails,
    categoryCounts,
    allFonts,
    favoriteCount,
    installedCount,
    notInstalledCount,
    activeCount,
    library,
    setPreviewText,
    installStatusReady,
    installStatusMissingCount,
    installStatusSyncSuffix,
    expandedFilterGroups,
    setFilterGroupExpanded,
    selectedWatchedFolders,
    setSelectedWatchedFolders,
    folderCounts,
    selectedFormats,
    setSelectedFormats,
    formatCounts,
    selectedScripts,
    setSelectedScripts,
    scriptCounts,
    selectedCategory,
    setSelectedCategory,
    clearAdvancedFilters,
    newSharedTagName,
    setNewSharedTagName,
    createSharedTagOnlyFromInput,
    sharedTagList,
    selectedSharedTagName,
    setSelectedSharedTagName,
    openSharedTagMenu,
    sharedTagCounts,
    newTagName,
    setNewTagName,
    createTagOnlyFromInput,
    localTagList,
    selectedTagName,
    setSelectedTagName,
    openTagMenu,
    localTagCounts,
    addFolder,
    selectedFolderId,
    setDatabasePageResult,
    setDatabaseQueryResult,
    setSelectedFolderId,
    expandedFolderIds,
    dropHoverFolderId,
    setDropHoverFolderId,
    selectFolderFilter,
    openFolderMenu,
    fontIdsFromDropEvent,
    assignFontsToFolder,
    toggleFolderExpanded,
    flatFolderNodes,
    setDeveloperStatusLog,
    latestIndexProgress,
    developerArchitecture,
    developerSchedulerStatus,
    developerMigrationDiagnostics,
    developerSharedMetadataDiagnostics,
    setDeveloperSharedMetadataDiagnostics,
    latestBackgroundTaskEvent,
    developerTasks,
    developerStatusLog,
    timeSortMode,
    sortMode,
    viewMode,
    cardPoolViewMode,
    setCardPoolViewMode,
    listPreviewFontSize,
    setListPreviewFontSize,
    updatePageToolbar,
    updateViewModeWithScroll,
    search,
    selectedFontIds,
    activateFontsBatch,
    deactivateFontsBatch,
    deleteFontsBatch,
    uninstallFontsBatch,
    toggleFontDeleteProtection,
    setSelectedFontIds,
    closeDetail,
    fontScrollerRef,
    handleFontScroll,
    beginMarqueeSelection,
    virtualLayout,
    cardPoolViewLayout,
    renderFontCard,
    databasePageReady,
    visibleFontTotal,
    visibleFonts,
    fontFamilyGroupResult,
    fontFamilyGroupLoading,
    fontFamilyGroupError,
    expandedFontFamilyIds,
    toggleFontFamilyExpanded,
    selectedFont,
    previewFamilies,
    selectedPreviewFamily,
    nativeDetailImage,
    toggleFontFavorite,
    installSelected,
    removeSelected,
    activateSelected,
    deactivateSelected,
    assignTagName,
    setAssignTagName,
    handleLocalTagInputKeyDown,
    localTagSuggestions,
    activeLocalTagSuggestionIndex,
    setActiveLocalTagSuggestionIndex,
    addTagToSelectedByName,
    removeTagFromSelected,
    assignSharedTagName,
    setAssignSharedTagName,
    handleSharedTagInputKeyDown,
    sharedTagSuggestions,
    activeSharedTagSuggestionIndex,
    setActiveSharedTagSuggestionIndex,
    addSharedTagToSelectedByName,
    removeSharedTagFromSelected,
    updateFont,
    applyInstallCompareToFont,
    renameTarget,
    setRenameTarget,
    renameValue,
    setRenameValue,
    confirmRename,
    deleteTarget,
    setDeleteTarget,
    confirmDelete,
    folderChildTarget,
    setFolderChildTarget,
    newFolderName,
    setNewFolderName,
    createSubfolder,
    selectionRect,
    normalizedSelectionRect,
    contextMenu,
    contextSelectedFonts,
    selectionLabel,
    runFontContextAction,
    runContextBatchActivate,
    runContextBatchDeactivate,
    runContextRefreshFolder,
    runContextRename,
    runContextAddSubfolder,
    runContextDelete,
    leaseLockConflictNotice,
    setLeaseLockConflictNotice,
  } = props

  return (
    <div className="app">
      <AppTopbar
        themeMode={themeMode}
        setThemeMode={setThemeMode}
        indexingActive={indexingActive}
        cacheMenuOpen={cacheMenuOpen}
        setCacheMenuOpen={setCacheMenuOpen}
        rescan={rescan}
        cancelIndexing={cancelIndexing}
        rebuildScanCache={rebuildScanCache}
        clearAllCacheAction={clearAllCacheAction}
      />

      <AppLayout
        detailVisible={detailVisible}
        renderSidebar={(sidebarCollapsed, setSidebarCollapsed) => (
          <AppSidebar
            sidebarCollapsed={sidebarCollapsed}
            setSidebarCollapsed={setSidebarCollapsed}
            sidebarPage={sidebarPage}
            setSidebarPage={setSidebarPage}
            activeFilter={activeFilter}
            setActiveFilter={setActiveFilter}
            advancedFilterCount={advancedFilterCount}
            refreshDeveloperStatusDetails={refreshDeveloperStatusDetails}
            categoryCounts={categoryCounts}
            allFonts={allFonts}
            favoriteCount={favoriteCount}
            installedCount={installedCount}
            notInstalledCount={notInstalledCount}
            activeCount={activeCount}
            previewText={library.previewText}
            setPreviewText={setPreviewText}
            installStatusReady={installStatusReady}
            installStatusMissingCount={installStatusMissingCount}
            installStatusSyncSuffix={installStatusSyncSuffix}
            expandedFilterGroups={expandedFilterGroups}
            setFilterGroupExpanded={setFilterGroupExpanded}
            selectedWatchedFolders={selectedWatchedFolders}
            setSelectedWatchedFolders={setSelectedWatchedFolders}
            library={library}
            folderCounts={folderCounts}
            selectedFormats={selectedFormats}
            setSelectedFormats={setSelectedFormats}
            formatCounts={formatCounts}
            selectedScripts={selectedScripts}
            setSelectedScripts={setSelectedScripts}
            scriptCounts={scriptCounts}
            selectedCategory={selectedCategory}
            setSelectedCategory={setSelectedCategory}
            clearAdvancedFilters={clearAdvancedFilters}
            newSharedTagName={newSharedTagName}
            setNewSharedTagName={setNewSharedTagName}
            createSharedTagOnlyFromInput={createSharedTagOnlyFromInput}
            sharedTagList={sharedTagList}
            selectedSharedTagName={selectedSharedTagName}
            setSelectedSharedTagName={setSelectedSharedTagName}
            openSharedTagMenu={openSharedTagMenu}
            sharedTagCounts={sharedTagCounts}
            newTagName={newTagName}
            setNewTagName={setNewTagName}
            createTagOnlyFromInput={createTagOnlyFromInput}
            localTagList={localTagList}
            selectedTagName={selectedTagName}
            setSelectedTagName={setSelectedTagName}
            openTagMenu={openTagMenu}
            localTagCounts={localTagCounts}
            addFolder={addFolder}
            selectedFolderId={selectedFolderId}
            setDatabasePageResult={setDatabasePageResult}
            setDatabaseQueryResult={setDatabaseQueryResult}
            setSelectedFolderId={setSelectedFolderId}
            expandedFolderIds={expandedFolderIds}
            dropHoverFolderId={dropHoverFolderId}
            setDropHoverFolderId={setDropHoverFolderId}
            selectFolderFilter={selectFolderFilter}
            openFolderMenu={openFolderMenu}
            fontIdsFromDropEvent={fontIdsFromDropEvent}
            assignFontsToFolder={assignFontsToFolder}
            toggleFolderExpanded={toggleFolderExpanded}
            flatFolderNodes={flatFolderNodes}
            setDeveloperStatusLog={setDeveloperStatusLog}
          />
        )}
      >
        <FontListPanel
          sidebarPage={sidebarPage}
          refreshDeveloperStatusDetails={refreshDeveloperStatusDetails}
          status={status}
          latestIndexProgress={latestIndexProgress}
          developerArchitecture={developerArchitecture}
          developerSchedulerStatus={developerSchedulerStatus}
          developerMigrationDiagnostics={developerMigrationDiagnostics}
          developerSharedMetadataDiagnostics={developerSharedMetadataDiagnostics}
          setDeveloperSharedMetadataDiagnostics={setDeveloperSharedMetadataDiagnostics}
          latestBackgroundTaskEvent={latestBackgroundTaskEvent}
          developerTasks={developerTasks}
          developerStatusLog={developerStatusLog}
          timeSortMode={timeSortMode}
          sortMode={sortMode}
          viewMode={viewMode}
          cardPoolViewMode={cardPoolViewMode}
          activeFilter={activeFilter}
          setCardPoolViewMode={setCardPoolViewMode}
          listPreviewFontSize={listPreviewFontSize}
          setListPreviewFontSize={setListPreviewFontSize}
          updatePageToolbar={updatePageToolbar}
          updateViewModeWithScroll={updateViewModeWithScroll}
          search={search}
          selectedFontIds={selectedFontIds}
          library={library}
          activateFontsBatch={activateFontsBatch}
          deactivateFontsBatch={deactivateFontsBatch}
          deleteFontsBatch={deleteFontsBatch}
          uninstallFontsBatch={uninstallFontsBatch}
          toggleFontDeleteProtection={toggleFontDeleteProtection}
          setSelectedFontIds={setSelectedFontIds}
          closeDetail={closeDetail}
          fontScrollerRef={fontScrollerRef}
          handleFontScroll={handleFontScroll}
          beginMarqueeSelection={beginMarqueeSelection}
          virtualLayout={virtualLayout}
          viewLayout={cardPoolViewLayout}
          renderFontCard={renderFontCard}
          databasePageReady={databasePageReady}
          visibleFontTotal={visibleFontTotal}
          visibleFonts={visibleFonts}
          fontFamilyGroupResult={fontFamilyGroupResult}
          fontFamilyGroupLoading={fontFamilyGroupLoading}
          fontFamilyGroupError={fontFamilyGroupError}
          expandedFontFamilyIds={expandedFontFamilyIds}
          toggleFontFamilyExpanded={toggleFontFamilyExpanded}
        />

        <FontDetailPanel
          visible={detailVisible}
          selectedFont={selectedFont}
          previewText={library.previewText}
          previewFamilies={previewFamilies}
          selectedPreviewFamily={selectedPreviewFamily}
          nativeDetailImage={nativeDetailImage}
          toggleFontFavorite={toggleFontFavorite}
          installSelected={installSelected}
          removeSelected={removeSelected}
          activateSelected={activateSelected}
          deactivateSelected={deactivateSelected}
          toggleFontDeleteProtection={toggleFontDeleteProtection}
          assignTagName={assignTagName}
          setAssignTagName={setAssignTagName}
          handleLocalTagInputKeyDown={handleLocalTagInputKeyDown}
          localTagSuggestions={localTagSuggestions}
          activeLocalTagSuggestionIndex={activeLocalTagSuggestionIndex}
          setActiveLocalTagSuggestionIndex={setActiveLocalTagSuggestionIndex}
          addTagToSelectedByName={addTagToSelectedByName}
          removeTagFromSelected={removeTagFromSelected}
          assignSharedTagName={assignSharedTagName}
          setAssignSharedTagName={setAssignSharedTagName}
          handleSharedTagInputKeyDown={handleSharedTagInputKeyDown}
          sharedTagSuggestions={sharedTagSuggestions}
          activeSharedTagSuggestionIndex={activeSharedTagSuggestionIndex}
          setActiveSharedTagSuggestionIndex={setActiveSharedTagSuggestionIndex}
          addSharedTagToSelectedByName={addSharedTagToSelectedByName}
          removeSharedTagFromSelected={removeSharedTagFromSelected}
          updateFont={updateFont}
          applyCompare={applyInstallCompareToFont}
        />
      </AppLayout>

      <AppOverlays
        renameTarget={renameTarget}
        setRenameTarget={setRenameTarget}
        renameValue={renameValue}
        setRenameValue={setRenameValue}
        confirmRename={confirmRename}
        deleteTarget={deleteTarget}
        setDeleteTarget={setDeleteTarget}
        confirmDelete={confirmDelete}
        folderChildTarget={folderChildTarget}
        setFolderChildTarget={setFolderChildTarget}
        newFolderName={newFolderName}
        setNewFolderName={setNewFolderName}
        createSubfolder={createSubfolder}
        selectionRect={selectionRect}
        normalizedSelectionRect={normalizedSelectionRect}
        contextMenu={contextMenu}
        contextSelectedFonts={contextSelectedFonts}
        selectionLabel={selectionLabel}
        runFontContextAction={runFontContextAction}
        deleteFontsBatch={deleteFontsBatch}
        uninstallFontsBatch={uninstallFontsBatch}
        toggleFontDeleteProtection={toggleFontDeleteProtection}
        runContextBatchActivate={runContextBatchActivate}
        runContextBatchDeactivate={runContextBatchDeactivate}
        runContextRefreshFolder={runContextRefreshFolder}
        runContextRename={runContextRename}
        runContextAddSubfolder={runContextAddSubfolder}
        runContextDelete={runContextDelete}
        leaseLockConflictNotice={leaseLockConflictNotice}
        setLeaseLockConflictNotice={setLeaseLockConflictNotice}
      />

      {IS_DEVELOPMENT && <footer className="statusbar">{status}</footer>}
    </div>
  )
}
